// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
void glue_modbus_handler(struct mg_modbus_req *req) {

  // This is just a stab
#define READ_COIL(i) (i)
#define WRITE_COIL(i, val) MG_INFO(("coil %d = %d", (i), (val)));

  // You can process other Modbus commands, too. See
  // https://github.com/cesanta/mongoose/blob/master/src/modbus.h
  if (req->func == MG_MODBUS_FUNC_READ_COILS) {
    for (uint16_t i = 0; i < req->len; i++) {
      req->u.bits[i] = READ_COIL(req->addr + i);
    }
  } else if (req->func == MG_MODBUS_FUNC_WRITE_MULTIPLE_COILS) {
    for (uint16_t i = 0; i < req->len; i++) {
      WRITE_COIL(req->addr + i, req->u.bits[i]);
    }
  } else {
    req->error = MG_MODBUS_ERR_DEVICE_FAILURE;
  }
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct holding_registers s_holding_registers[] = {
  {0},
  {0},
  {0},
};
bool glue_get_holding_registers(struct holding_registers *data, size_t i) {
  size_t array_size = sizeof(s_holding_registers) / sizeof(s_holding_registers[0]);
  if (i >= array_size) return false;
  *data = s_holding_registers[i];  // Sync with your device
  return true;
}
void glue_set_holding_registers(struct holding_registers *data, size_t i) {
  size_t array_size = sizeof(s_holding_registers) / sizeof(s_holding_registers[0]);
  if (i < array_size) s_holding_registers[i] = *data; // Sync with your device
}